package edu.upenn.cis.cis455.storage.dynamoDb;


import com.amazonaws.services.dynamodbv2.datamodeling.*;
import edu.upenn.cis.cis455.model.urlDataInfo.DocOnlyInfo;

@DynamoDBTable(tableName="DocOnlyInfoTest")
public class DocOnlyInfoDynamoDb {

    private String id;
    private String content;
    private Integer contentLength = 0;
    private String hashString;

    public DocOnlyInfoDynamoDb() {
    }

    public DocOnlyInfoDynamoDb(DocOnlyInfo docOnlyInfo) {

        this.id = docOnlyInfo.getId();
        this.content = docOnlyInfo.getContent();
        this.contentLength = docOnlyInfo.getContentLength();
        this.hashString = docOnlyInfo.getHash();
    }



    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getContent() {
        return content;
    }

    public void setContent(String content) {
        this.content = content;
    }

    public int getContentLength() {
        return contentLength;
    }

    public void setContentLength(int contentLength) {
        this.contentLength = contentLength;
    }

    @DynamoDBIndexHashKey(globalSecondaryIndexName = "hashIndex")
    public String getHashString() {
        return hashString;
    }

    public void setHashString(String hash) {
        this.hashString = hash;
    }
}
